name: sitkpy

# Use the dev label because we will use an RC and not a
# retular release (2.0.0), go back to regular channel
# when 2.0.0 is released
channels:
  - defaults
  - simpleitk/label/dev
  - conda-forge

dependencies:
  - python=3.8
  - jupyter
  - matplotlib
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - numba
  - multiprocess
  - SimpleITK>1.2.4
