name: sitkpy

channels:
  - defaults
  - simpleitk
  - conda-forge

dependencies:
  - python=3.8
  - jupyter
  - matplotlib
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - numba
  - multiprocess
  - SimpleITK>=2.2.0
