name: Windows Pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      testPyPi:
        description: 'Use test PyPi?'     
        required: true
        default: 'false'

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          Data
        key: notebook-data-{{ checksum "Data/manifest.json" }}
        restore-keys: |
          notebook-data-{{ checksum "Data/manifest.json" }}
          notebook-data-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m ipykernel install --user
        If ( "${{ github.event.inputs.testPyPi }}"  -eq 'true') {
          Write-Output "*** Using Test PyPi ***"
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple SimpleITK
        }
        pip install -r requirements_dev.txt
        jupyter nbextension enable --py widgetsnbextension
    - name: Patch asyncio library for 3.8
      run: python .\.github\workflows\patch-asyncio.py
      if: matrix.python-version == '3.8' 
    - name: Activate environment and run the test
      env: 
        SIMPLE_ITK_MEMORY_CONSTRAINED_ENVIRONMENT: 1
      run: |
        pytest -v --tb=short tests/test_notebooks.py::Test_notebooks::test_python_notebook